---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: deploy-list
rules:
- apiGroups: ["", "extension", "apps"]
  resources: ["deployments", "services", "pods", "endpoints", "secrets"]
  verbs: ["get","list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-list-rb
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: deploy-list
  apiGroup: ""
